/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hangmandm;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;


/**
 * *************************************************************
 * file: GamePanel.java authors: S. Araya, D. Menkir, J Ong 
 * class: CS 2450 – User Interface Design and Programming 
 *
 * assignment: program 1 date last modified: 9/26/2022
 *
 * purpose: This panel hosts the hangman game visuals. Logic is handled in GameLogic.java.
 *
 ***************************************************************
 */
public class GamePanel extends javax.swing.JPanel {
    
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        Timer t = new Timer(1000, updateClockAction);
        t.start();
        
        
        
        /*
        letter1.setText(" ");
        letter2.setText(" ");
        letter3.setText(" ");
        letter4.setText(" ");
        letter5.setText(" ");
        letter6.setText(" ");
        letter7.setText(" ");
        letter8.setText(" ");
        letter9.setText(" ");
        letter10.setText(" ");
        */
        
        //for (int i=0; i<GameLogic.currentWord.length(); i++){
        //    lettersLong[i].setText(GameLogic.currentWordReverse[i]);
        //}
        
        
        initComponents();
        
        
        images[0] = image0;
        images[1] = image1;
        images[2] = image2;
        images[3] = image3;
        images[4] = image4;
        images[5] = image5;
        images[6] = image6;
        
        
        lettersLong[0] = letter1;
        lettersLong[1] = letter2;
        lettersLong[2] = letter3;
        lettersLong[3] = letter4;
        lettersLong[4] = letter5;
        lettersLong[5] = letter6;
        lettersLong[6] = letter7;
        lettersLong[7] = letter8;
        lettersLong[8] = letter9;
        lettersLong[9] = letter10;
        
        spriteReset();
        letterReset();
    }
    
    //CODE TO SWITCH IMAGES
    ImageIcon[] images = new ImageIcon[7];
    
    ImageIcon image0 = new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/HangmanSprite_0.png"));
    ImageIcon image1 = new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/HangmanSprite_1.png"));
    ImageIcon image2 = new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/HangmanSprite_2.png"));
    ImageIcon image3 = new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/HangmanSprite_3.png"));
    ImageIcon image4 = new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/HangmanSprite_4.png"));
    ImageIcon image5 = new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/HangmanSprite_5.png"));
    ImageIcon image6 = new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/HangmanSprite_0.png"));
    
    
    
    private void spriteCheck(){
        spriteReset();
        System.out.println("nextSprite() called");
        int i = 0;
        while (i!=GameLogic.incorrectGuesses){
            i++;
        }
        
        hangmanSprite.setIcon(images[i]);
    }

    
    public void spriteReset(){
        hangmanSprite.setIcon(images[0]);
    }
    //IMAGE SWITCH CODE END
    
    
    //CODE TO SWITCH LETTERS
    private static JLabel[] lettersLong = new JLabel[10];
    
    public static void letterCheck(){
        JLabel[] letters = new JLabel[GameLogic.currentWord.length()];
        for (int i=0; i<GameLogic.currentWordReverse.length; i++){
            lettersLong[i].setText(GameLogic.currentWordReverse[i]);
            lettersLong[i].setVisible(true);
        }
        //letter1.setText(GameLogic.currentWordReverse[0]);
    }
    
    public static void letterReset(){
        for (int i=0; i<10; i++){
            lettersLong[i].setText(" ");
            lettersLong[i].setVisible(false);
        }
    }
    //LETTER SWITCH CODE END
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonA = new javax.swing.JButton();
        buttonB = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        buttonD = new javax.swing.JButton();
        buttonE = new javax.swing.JButton();
        buttonF = new javax.swing.JButton();
        buttonG = new javax.swing.JButton();
        buttonH = new javax.swing.JButton();
        buttonI = new javax.swing.JButton();
        buttonJ = new javax.swing.JButton();
        buttonK = new javax.swing.JButton();
        buttonL = new javax.swing.JButton();
        buttonM = new javax.swing.JButton();
        buttonN = new javax.swing.JButton();
        buttonO = new javax.swing.JButton();
        buttonP = new javax.swing.JButton();
        buttonQ = new javax.swing.JButton();
        buttonR = new javax.swing.JButton();
        buttonS = new javax.swing.JButton();
        buttonT = new javax.swing.JButton();
        buttonU = new javax.swing.JButton();
        buttonV = new javax.swing.JButton();
        buttonW = new javax.swing.JButton();
        buttonX = new javax.swing.JButton();
        buttonY = new javax.swing.JButton();
        buttonZ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hangmanSprite = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        letter1 = new javax.swing.JLabel();
        letter2 = new javax.swing.JLabel();
        letter3 = new javax.swing.JLabel();
        letter4 = new javax.swing.JLabel();
        letter5 = new javax.swing.JLabel();
        letter6 = new javax.swing.JLabel();
        letter7 = new javax.swing.JLabel();
        letter8 = new javax.swing.JLabel();
        letter9 = new javax.swing.JLabel();
        letter10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jButton1.setText("SKIP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonA.setText("A");
        buttonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAActionPerformed(evt);
            }
        });

        buttonB.setText("B");
        buttonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBActionPerformed(evt);
            }
        });

        buttonC.setText("C");
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });

        buttonD.setText("D");
        buttonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDActionPerformed(evt);
            }
        });

        buttonE.setText("E");
        buttonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEActionPerformed(evt);
            }
        });

        buttonF.setText("F");
        buttonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFActionPerformed(evt);
            }
        });

        buttonG.setText("G");
        buttonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGActionPerformed(evt);
            }
        });

        buttonH.setText("H");
        buttonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHActionPerformed(evt);
            }
        });

        buttonI.setText("I");
        buttonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIActionPerformed(evt);
            }
        });

        buttonJ.setText("J");
        buttonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJActionPerformed(evt);
            }
        });

        buttonK.setText("K");
        buttonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKActionPerformed(evt);
            }
        });

        buttonL.setText("L");
        buttonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLActionPerformed(evt);
            }
        });

        buttonM.setText("M");
        buttonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMActionPerformed(evt);
            }
        });

        buttonN.setText("N");
        buttonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNActionPerformed(evt);
            }
        });

        buttonO.setText("O");
        buttonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOActionPerformed(evt);
            }
        });

        buttonP.setText("P");
        buttonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPActionPerformed(evt);
            }
        });

        buttonQ.setText("Q");
        buttonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQActionPerformed(evt);
            }
        });

        buttonR.setText("R");
        buttonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRActionPerformed(evt);
            }
        });

        buttonS.setText("S");
        buttonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSActionPerformed(evt);
            }
        });

        buttonT.setText("T");
        buttonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTActionPerformed(evt);
            }
        });

        buttonU.setText("U");
        buttonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUActionPerformed(evt);
            }
        });

        buttonV.setText("V");
        buttonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVActionPerformed(evt);
            }
        });

        buttonW.setText("W");
        buttonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWActionPerformed(evt);
            }
        });

        buttonX.setText("X");
        buttonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXActionPerformed(evt);
            }
        });

        buttonY.setText("Y");
        buttonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYActionPerformed(evt);
            }
        });

        buttonZ.setText("Z");
        buttonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZActionPerformed(evt);
            }
        });

        jLabel1.setText(dtf.format(now));

        hangmanSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/HangmanSprite_0.png"))); // NOI18N

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        letter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/Line.png"))); // NOI18N
        letter1.setText("?");
        letter1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        letter1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letter1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        letter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letter2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/Line.png"))); // NOI18N
        letter2.setText("?");
        letter2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        letter2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letter2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        letter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letter3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/Line.png"))); // NOI18N
        letter3.setText("?");
        letter3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        letter3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letter3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        letter4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letter4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/Line.png"))); // NOI18N
        letter4.setText("?");
        letter4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        letter4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letter4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        letter5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letter5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/Line.png"))); // NOI18N
        letter5.setText("?");
        letter5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        letter5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letter5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        letter6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letter6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/Line.png"))); // NOI18N
        letter6.setText("?");
        letter6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        letter6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letter6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        letter7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letter7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/Line.png"))); // NOI18N
        letter7.setText("?");
        letter7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        letter7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letter7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        letter8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letter8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/Line.png"))); // NOI18N
        letter8.setText("?");
        letter8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        letter8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letter8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        letter9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letter9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/Line.png"))); // NOI18N
        letter9.setText("?");
        letter9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        letter9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letter9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        letter10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letter10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/Line.png"))); // NOI18N
        letter10.setText("?");
        letter10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        letter10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letter10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(letter1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letter2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letter3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letter4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letter5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letter6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letter7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letter8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letter9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letter10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(letter1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(letter3)
                        .addComponent(letter2)
                        .addComponent(letter4)
                        .addComponent(letter5)
                        .addComponent(letter6)
                        .addComponent(letter7)
                        .addComponent(letter8)
                        .addComponent(letter9)
                        .addComponent(letter10)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonZ))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonR))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonI)))
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hangmanSprite)
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addComponent(hangmanSprite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonA)
                    .addComponent(buttonB)
                    .addComponent(buttonC)
                    .addComponent(buttonD)
                    .addComponent(buttonE)
                    .addComponent(buttonF)
                    .addComponent(buttonG)
                    .addComponent(buttonH)
                    .addComponent(buttonI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonN)
                    .addComponent(buttonO)
                    .addComponent(buttonP)
                    .addComponent(buttonQ)
                    .addComponent(buttonJ)
                    .addComponent(buttonK)
                    .addComponent(buttonL)
                    .addComponent(buttonM)
                    .addComponent(buttonR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonS)
                    .addComponent(buttonT)
                    .addComponent(buttonU)
                    .addComponent(buttonV)
                    .addComponent(buttonW)
                    .addComponent(buttonX)
                    .addComponent(buttonY)
                    .addComponent(buttonZ))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HangmanDM.cardLayout.show(HangmanDM.frame.getContentPane(), "menu");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        spriteReset();
        letterReset();
        HangmanDM.cardLayout.show(HangmanDM.frame.getContentPane(), "credits");
    }//GEN-LAST:event_jButton1ActionPerformed

    //CLOCK FUNCTIONALITY
    private DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd  HH:mm:ss");  
    private LocalDateTime now = LocalDateTime.now();
    
    ActionListener updateClockAction = new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            // Assumes clock is a JLabel
            now = LocalDateTime.now();
            jLabel1.setText(dtf.format(now)); 
            //spriteCheck();
            //letterCheck();
            if(GameLogic.winFlag || GameLogic.gameOverFlag){
                spriteReset();
                letterReset();
            }
        }
    };
    //CLOCK FUNTIONALITY END
    
    
    
    
    //LETTER BUTTONS
    private void buttonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("a"));
        spriteCheck();
        letterCheck();
        buttonA.setEnabled(false);
    }//GEN-LAST:event_buttonAActionPerformed

    private void buttonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("b"));
        spriteCheck();
        letterCheck();
        buttonB.setEnabled(false);
    }//GEN-LAST:event_buttonBActionPerformed

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("c"));
        spriteCheck();
        letterCheck();
        buttonC.setEnabled(false);
    }//GEN-LAST:event_buttonCActionPerformed

    private void buttonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("d"));
        spriteCheck();
        letterCheck();
        buttonD.setEnabled(false);
    }//GEN-LAST:event_buttonDActionPerformed

    private void buttonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("e"));
        spriteCheck();
        letterCheck();
        buttonE.setEnabled(false);
    }//GEN-LAST:event_buttonEActionPerformed

    private void buttonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("f"));
        spriteCheck();
        letterCheck();
        buttonF.setEnabled(false);
    }//GEN-LAST:event_buttonFActionPerformed

    private void buttonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("g"));
        spriteCheck();
        letterCheck();
        buttonG.setEnabled(false);
    }//GEN-LAST:event_buttonGActionPerformed

    private void buttonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("h"));
        spriteCheck();
        letterCheck();
        buttonH.setEnabled(false);
    }//GEN-LAST:event_buttonHActionPerformed

    private void buttonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("i"));
        spriteCheck();
        letterCheck();
        buttonI.setEnabled(false);
    }//GEN-LAST:event_buttonIActionPerformed

    private void buttonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("j"));
        spriteCheck();
        letterCheck();
        buttonJ.setEnabled(false);
    }//GEN-LAST:event_buttonJActionPerformed

    private void buttonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("k"));
        spriteCheck();
        letterCheck();
        buttonK.setEnabled(false);
    }//GEN-LAST:event_buttonKActionPerformed

    private void buttonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("l"));
        spriteCheck();
        letterCheck();
        buttonL.setEnabled(false);
    }//GEN-LAST:event_buttonLActionPerformed

    private void buttonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("m"));
        spriteCheck();
        letterCheck();
        buttonM.setEnabled(false);
    }//GEN-LAST:event_buttonMActionPerformed

    private void buttonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("n"));
        spriteCheck();
        letterCheck();
        buttonN.setEnabled(false);
    }//GEN-LAST:event_buttonNActionPerformed

    private void buttonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("o"));
        spriteCheck();
        letterCheck();
        buttonO.setEnabled(false);
    }//GEN-LAST:event_buttonOActionPerformed

    private void buttonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("p"));
        spriteCheck();
        letterCheck();
        buttonP.setEnabled(false);
    }//GEN-LAST:event_buttonPActionPerformed

    private void buttonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("q"));
        spriteCheck();
        letterCheck();
        buttonQ.setEnabled(false);
    }//GEN-LAST:event_buttonQActionPerformed

    private void buttonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("r"));
        spriteCheck();
        letterCheck();
        buttonR.setEnabled(false);
    }//GEN-LAST:event_buttonRActionPerformed

    private void buttonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("s"));
        spriteCheck();
        letterCheck();
        buttonS.setEnabled(false);
    }//GEN-LAST:event_buttonSActionPerformed

    private void buttonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("t"));
        spriteCheck();
        letterCheck();
        buttonT.setEnabled(false);
    }//GEN-LAST:event_buttonTActionPerformed

    private void buttonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("u"));
        spriteCheck();
        letterCheck();
        buttonU.setEnabled(false);
    }//GEN-LAST:event_buttonUActionPerformed

    private void buttonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("v"));
        spriteCheck();
        letterCheck();
        buttonV.setEnabled(false);
    }//GEN-LAST:event_buttonVActionPerformed

    private void buttonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("w"));
        spriteCheck();
        letterCheck();
        buttonW.setEnabled(false);
    }//GEN-LAST:event_buttonWActionPerformed

    private void buttonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("x"));
        spriteCheck();
        letterCheck();
        buttonX.setEnabled(false);
    }//GEN-LAST:event_buttonXActionPerformed

    private void buttonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("y"));
        spriteCheck();
        letterCheck();
        buttonY.setEnabled(false);
    }//GEN-LAST:event_buttonYActionPerformed

    private void buttonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZActionPerformed
        // TODO add your handling code here:
        System.out.println(GameLogic.isCorrect("z"));
        spriteCheck();
        letterCheck();
        buttonZ.setEnabled(false);
    }//GEN-LAST:event_buttonZActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hangmanSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmanSprites/HangmanSprite_1.png")));
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void buttonReset(){
        buttonA.setEnabled(true);
        buttonB.setEnabled(true);
        buttonC.setEnabled(true);
        buttonD.setEnabled(true);
        buttonE.setEnabled(true);
        buttonF.setEnabled(true);
        buttonG.setEnabled(true);
        buttonH.setEnabled(true);
        buttonI.setEnabled(true);
        buttonJ.setEnabled(true);
        buttonK.setEnabled(true);
        buttonL.setEnabled(true);
        buttonM.setEnabled(true);
        buttonN.setEnabled(true);
        buttonO.setEnabled(true);
        buttonP.setEnabled(true);
        buttonQ.setEnabled(true);
        buttonR.setEnabled(true);
        buttonS.setEnabled(true);
        buttonT.setEnabled(true);
        buttonU.setEnabled(true);
        buttonV.setEnabled(true);
        buttonW.setEnabled(true);
        buttonX.setEnabled(true);
        buttonY.setEnabled(true);
        buttonZ.setEnabled(true);
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton buttonA;
    private static javax.swing.JButton buttonB;
    private static javax.swing.JButton buttonC;
    private static javax.swing.JButton buttonD;
    private static javax.swing.JButton buttonE;
    private static javax.swing.JButton buttonF;
    private static javax.swing.JButton buttonG;
    private static javax.swing.JButton buttonH;
    private static javax.swing.JButton buttonI;
    private static javax.swing.JButton buttonJ;
    private static javax.swing.JButton buttonK;
    private static javax.swing.JButton buttonL;
    private static javax.swing.JButton buttonM;
    private static javax.swing.JButton buttonN;
    private static javax.swing.JButton buttonO;
    private static javax.swing.JButton buttonP;
    private static javax.swing.JButton buttonQ;
    private static javax.swing.JButton buttonR;
    private static javax.swing.JButton buttonS;
    private static javax.swing.JButton buttonT;
    private static javax.swing.JButton buttonU;
    private static javax.swing.JButton buttonV;
    private static javax.swing.JButton buttonW;
    private static javax.swing.JButton buttonX;
    private static javax.swing.JButton buttonY;
    private static javax.swing.JButton buttonZ;
    public static javax.swing.JLabel hangmanSprite;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JLabel letter1;
    private static javax.swing.JLabel letter10;
    private static javax.swing.JLabel letter2;
    private static javax.swing.JLabel letter3;
    private static javax.swing.JLabel letter4;
    private static javax.swing.JLabel letter5;
    private static javax.swing.JLabel letter6;
    private static javax.swing.JLabel letter7;
    private static javax.swing.JLabel letter8;
    private static javax.swing.JLabel letter9;
    // End of variables declaration//GEN-END:variables
}
