/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hangmandm;

import javax.swing.SwingUtilities; 
import javax.swing.JFrame; 
import javax.swing.JPanel; 
import javax.swing.BorderFactory; 
import java.awt.Color; 
import java.awt.Dimension; 
import java.awt.Graphics; 
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author danie
 */
public class PongPanel extends javax.swing.JPanel {

    private int x;
    private int y;
    private final int border;
    private boolean yDirection; //true is up, false is down
    private boolean xDirection; // true is right, false is left
    private boolean startFlag;
    
    /**
     * Creates new form PongPanel
     */
    public PongPanel() {
        initComponents();
        x = 300;
        y = 200;
        border = 25;
        yDirection = true;
        xDirection = true;
        startFlag = false;
        
    }

    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        
        g.fillOval(x, y, border, border);
        moveBall();
        repaint();
        try {
                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(PongPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void moveBall()
    {
        if(xDirection)
        {
            x = x+1;
        }
        
        if(yDirection)
        {
            y = y+1;
        }
        
        
        if (y>=getHeight()-border-1 || !yDirection)
        {
            y = y-1;
            yDirection = false;
        }
        if(y <=23-border || yDirection)
        {
            y = y+1;
            yDirection = true;
        }
        
        if(x>=getWidth()-border-1 || !xDirection)
        {
            x = x-1;
            xDirection = false;
        }
        if(x <=21-border || xDirection)
        {
            x = x+1;
            xDirection = true;
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));

        jButton1.setText("Start Ball Movement");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jButton1)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        startFlag = !startFlag;
        while(startFlag)
        {
            
            repaint();
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(PongPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            jButton1.setText("Stop Ball Movement");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
